<a href="https://colab.research.google.com/github/Syamabintafaruque/Hello_Github_Faruque/blob/main/Homework_Pandas_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NAME : SYAMA BINTA FARUQUE

ID : 20231084

HOMEWORK #  Pandas and Numpy exercises for Data Analysis


1. Numpy Array Exercises

In [ ]:
# How to create an empty and a full Numpy array?
import numpy as np
# Create an empty array
x = np.empty((4,2), dtype=int)
print(x)
# Create a full array
y = np.full((3,3),7)
print(y)

# Create a Numpy array filled with all zeros

import numpy as np

#create numpy array with zeros
a = np.zeros((5,5), dtype=int)

#print numpy array
print(a)


# Create a Numpy array filled with all ones
import numpy as np

a = np.ones((2, 3))
print(a)

# Combining a one and a two-dimensional Numpy Array
# importing Numpy package
import numpy as np

num_1d = np.arange(5)
print("One dimensional array:")
print(num_1d)

num_2d = np.arange(10).reshape(2,5)
print("\nTwo dimensional array:")
print(num_2d)
 # Counts the number of non- zero values in the array
import numpy as np
x = np.array([[0, 15, 25], [25, 35, 45]])
print("Original array:")
print(x)
print("Number of non zero elements in the above array:")
print(np.count_nonzero(x))







[[29615040        0]
 [       0        0]
 [       0        0]
 [       0        0]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
One dimensional array:
[0 1 2 3 4]

Two dimensional array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
Original array:
[[ 0 15 25]
 [25 35 45]]
Number of non zero elements in the above array:
5


2. NumPy Matrix Exercises

In [ ]:
from numpy.matrixlib.defmatrix import matrix
# Get the maximum value from given matrix.
import numpy as np

# Create 2-D NumPy array
arr = np.array([[15,28,57],
                [99,65,34],
                [39,68,69],
                [37,55,88]])

# Get the maximum value of 2D NumPy array
arr1 = np.max(arr)
print(arr1)

# Get the maximum values of each column
arr1 = np.max(arr, axis=0)
print(arr1)

# Get the maximum values of each row
arr1 = np.max(arr, axis=1)
print(arr1)

# Get the minimum value from given matrix.
import numpy as np
a = np.array([[1,2],[3,4]])
matrix = [[1, 2], [3, 4]]
min(map(min, matrix))

# Find the number of rows and columns of a given matrix using NumPy
import numpy as np


matrix= np.arange(6).reshape((3, 2))

# Original matrix:
print(matrix)

# Number of rows and columns of the said matrix
print(matrix.shape)

# Adding and Subtracting Matrices in Python.
import numpy as np

# creating first matrix
A = np.array([[1, 2], [3, 4]])

# creating second matrix
B = np.array([[4, 5], [6, 7]])

print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)

# adding two matrix
print("Addition of two matrix")
print(np.add(A, B))

# importing numpy as np
import numpy as np


# creating first matrix
A = np.array([[3, 2], [5, 7]])

# creating second matrix
B = np.array([[4, 5], [6, 7]])

print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
# subtracting two matrix
print("Subtraction of two matrix")
print(np.subtract(A, B))

# Matrix Multiplication in NumPY
import numpy as np

arr1 = np.array([[3, 2],
                 [6, 4]])
arr2 = np.array([[5, 3],
                 [7, 8]])

arr_result = np.multiply(arr1, arr2)
print(arr_result)

# Ways to add row/columns in numpy array.
import numpy as np

# creating  numpy array
arr = np.array([[1, 2, 3, 4, 5],
                [5, 4, 3, 2, 1]])

row = np.array([6, 7, 8, 9, 1])

# Adding row to array using append() method
arr = np.append(arr, [row], axis=0)

# Array after adding the row.
print(arr)

import numpy as np
x = np.array([[10,20,30], [40,50,60]])
y = np.array([[100], [200]])
print(np.append(x, y, axis=1))

# Get the eigen values of a matrix
# importing numpy library
import numpy as np

# create numpy 2d-array
m = np.array([[1, 2, 3],
              [2, 3, 4],
              [4, 5, 6]])

print("Printing the Original square array:\n",
      m)

# finding eigenvalues and eigenvectors
w, v = np.linalg.eig(m)

# printing eigen values
print("Printing the Eigen values of the given square array:\n",
      w)

# printing eigen vectors
print("Printing Right eigenvectors of the given square array:\n",
      v)

# How to count the frequency of unique values in NumPy array
import numpy as np

#create NumPy array
my_array = np.array([1, 3, 3, 4, 4, 7, 8, 8])
#display unique values
np.unique(my_array)
#display total number of unique values
len(np.unique(my_array))

# How to get inverse a matrix using NumPy?
# Import required package
import numpy as np

# Taking a 4 * 4 matrix
A = np.array([[6, 1, 1, 3],
              [4, -2, 5, 1],
              [2, 8, 7, 6],
              [3, 1, 9, 7]])

# Calculating the inverse of the matrix
print(np.linalg.inv(A))

# How to calculate the determinant of a matrix using NumPy?
# importing Numpy package
import numpy as np

# creating a 2X2 Numpy matrix
n_array = np.array([[50, 29], [30, 44]])

# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)

# calculating the determinant of matrix
det = np.linalg.det(n_array)

print("\nDeterminant of given 2X2 matrix:")
print(int(det))

# Convert covariance matrix to correlation matrix using Python
import numpy as np

A = [45, 37, 42, 35, 39]
B = [38, 31, 26, 28, 33]
C = [10, 15, 17, 21, 12]

data = np.array([A, B, C])

cov_matrix = np.cov(data, bias=True)
print(cov_matrix)












99
[99 68 88]
[57 99 69 88]
[[0 1]
 [2 3]
 [4 5]]
(3, 2)
Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]
Printing elements of first matrix
[[3 2]
 [5 7]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Subtraction of two matrix
[[-1 -3]
 [-1  0]]
[[15  6]
 [42 32]]
[[1 2 3 4 5]
 [5 4 3 2 1]
 [6 7 8 9 1]]
[[ 10  20  30 100]
 [ 40  50  60 200]]
Printing the Original square array:
 [[1 2 3]
 [2 3 4]
 [4 5 6]]
Printing the Eigen values of the given square array:
 [ 1.08309519e+01 -8.30951895e-01  1.01486082e-16]
Printing Right eigenvectors of the given square array:
 [[ 0.34416959  0.72770285  0.40824829]
 [ 0.49532111  0.27580256 -0.81649658]
 [ 0.79762415 -0.62799801  0.40824829]]
[[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]
Numpy Matrix

3. NumPy Indexing Exercises

In [ ]:
# Replace NumPy array elements that doesn't satisfy the given conditon
import numpy as np

# Creating a 3-D Numpy array
n_arr = np.array([[[11, 25.5, 70.6], [30.9, 45.5, 55.9], [20.7, 45.8, 7.1]],
                  [[50.1, 65.9, 8.2], [70.4, 85.8, 10.3], [11.3, 22.2, 33.6]],
                  [[19.9, 69.7, 36.8], [1.2, 5.1, 24.4], [4.9, 20.8, 96.7]]])

print("Given array:")
print(n_arr)

print("\nReplace all elements of array which are less than 10 to Nan")
n_arr[n_arr < 10.] = np.nan

print("New array :\n")
print(n_arr)

# Return the indices of elements where the given condition is satisfied.
my_list = [4, 8, 12, 16, 25]

indexes = [
    index for index in range(len(my_list))
    if my_list[index] > 10
]

print(indexes)

# Replace negative value with zero in numpy array.
# Python code to demonstrate
# to replace negative values with 0
import numpy as np

ini_array1 = np.array([1, 2, -3, 4, -5, -6])

# printing initial arrays
print("initial array", ini_array1)

# code to replace all negative value with 0
result = np.where(ini_array1<0, 0, ini_array1)

# printing result
print("New resulting array: ", result)

# Replace NaN values with average of columns.
import numpy as np

# Initialising numpy array
ini_array = np.array([[1.3, 2.5, 3.6, np.nan],
                      [2.6, 3.3, np.nan, 5.5],
                      [2.1, 3.2, 5.4, 6.5]])

# printing initial array
print ("initial array", ini_array)

# replace nan with col means
res = np.where(np.isnan(ini_array), np.ma.array(ini_array,
               mask = np.isnan(ini_array)).mean(axis = 0), ini_array)

# printing final array
print ("final array", res)

# How to get values of an NumPy aaray at certain index positions?
# Importing Numpy module
import numpy as np

# Creating 2-D Numpy array
a1 = np.array([[11, 10, 22, 30],
               [14, 58, 88, 100]])

print("Array 1 :")
print(a1)

a2 = np.array([1, 15, 6, 40])
print("Array 2 :")
print(a2)

print("\nTake 1, 15 and 6 from Array 2 and put them in 1st,\
4th and 7th positions of Array 1")

a1.put([0, 3, 6], a2)

print("Resultant Array :")
print(a1)

# Find indices of elements equal to zero in a NumPy array
# importing Numpy package
import numpy as np

# creating a 3-D Numpy array
n_array = np.array([[0, 2, 3],
                    [4, 1, 0],
                    [0, 0, 2]])

print("Original array:")
print(n_array)

# finding indices of null elements
# using np.argwhere()
print("\nIndices of null elements:")
res = np.argwhere(n_array == 0)

print(res)

# How to access different rows of a multidimensional NumPy array?
import numpy as np

# Creating a 3X3 2-D Numpy array
arr = np.array([[15, 20, 35],
                [40, 5, 64],
                [80, 89, 96]])

print("Given Array :")
print(arr)

# Access the First and Last rows of array
res_arr = arr[[0,2]]
print("\nAccessed Rows :")
print(res_arr)

# How to remove columns in NumPy array that contains non-numeric values?
import numpy as np

# Creating 3X3 2-D Numpy array
n_arr = np.array([[10.5, 22.5, 3.8],
                  [23.45, 50, 78.7],
                  [41, np.nan, np.nan]])

print("Given array:")
print(n_arr)

print("\nRemove all rows containing non-numeric elements")
print(n_arr[~np.isnan(n_arr).any(axis=1)])

# Get row numbers of NumPy array having element larger than x
import numpy

# create numpy array
arr = numpy.array([[1, 2, 3, 4, 5],
                  [10, -3, 30, 4, 5],
                  [3, 2, 5, -4, 5],
                  [9, 7, 3, 6, 5]
                 ])

# declare specified value
X = 6

# view array
print("Given Array:\n", arr)





Given array:
[[[11.  25.5 70.6]
  [30.9 45.5 55.9]
  [20.7 45.8  7.1]]

 [[50.1 65.9  8.2]
  [70.4 85.8 10.3]
  [11.3 22.2 33.6]]

 [[19.9 69.7 36.8]
  [ 1.2  5.1 24.4]
  [ 4.9 20.8 96.7]]]

Replace all elements of array which are less than 10 to Nan
New array :

[[[11.  25.5 70.6]
  [30.9 45.5 55.9]
  [20.7 45.8  nan]]

 [[50.1 65.9  nan]
  [70.4 85.8 10.3]
  [11.3 22.2 33.6]]

 [[19.9 69.7 36.8]
  [ nan  nan 24.4]
  [ nan 20.8 96.7]]]
[2, 3, 4]
initial array [ 1  2 -3  4 -5 -6]
New resulting array:  [1 2 0 4 0 0]
initial array [[1.3 2.5 3.6 nan]
 [2.6 3.3 nan 5.5]
 [2.1 3.2 5.4 6.5]]
final array [[1.3 2.5 3.6 6. ]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]
Array 1 :
[[ 11  10  22  30]
 [ 14  58  88 100]]
Array 2 :
[ 1 15  6 40]

Take 1, 15 and 6 from Array 2 and put them in 1st,4th and 7th positions of Array 1
Resultant Array :
[[  1  10  22  15]
 [ 14  58   6 100]]
Original array:
[[0 2 3]
 [4 1 0]
 [0 0 2]]

Indices of null elements:
[[0 0]
 [1 2]
 [2 0]
 [2 1]]
Given Array :
[[15 20 3

4. NumPy Sorting and Searching Exercises

In [ ]:
# How to get the indices of the sorted array using NumPy in Python?
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
print("Original array:")
print(student_id)
i = np.argsort(student_id)
print("Indices of the sorted elements of a given array:")
print(i)

# Finding the k smallest values of a NumPy array.
import numpy as np
array1 = np.array([1, 6, 9, 2, 0.3, 4, 10, 2.7])
print("Original arrays:")
print(array1)
k = 4
result = np.argpartition(array1, k)
print("\nk smallest values:")
print(array1[result[:k]])

# How to get the n-largest values of an array ussing Numpy?
import numpy as np
x = np.arange(13)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

# Sort the values in a matrix.
import numpy as np

a = np.array([[1,4], [3,1]])
a.sort(axis=1)
a = np.array([[1, 4],
       [1, 3]])
a.sort(axis=0)
a

# Filter out integers from float NumPy array.
import numpy as np

# initialising array
ini_array = np.array([1.0, 1.4, 2.7, 2.0, 3.0, 2.0])

# printing initial array
print ("initial array : ", str(ini_array))

# filtering integers
result = ini_array[ini_array != ini_array.astype(int)]

# printing resultant
print ("final array", result)

# Find the indices into a sorted array.
import numpy as np
student_id = np.array([1050, 5400, 6250, 1674, 1685, 5237, 4545])
print("Original array:")
print(student_id)
i = np.argsort(student_id)
print("Indices of the sorted elements of a given array:")
print(i)


Original array:
[1023 5202 6230 1671 1682 5241 4532]
Indices of the sorted elements of a given array:
[0 3 4 6 1 5 2]
Original arrays:
[ 1.   6.   9.   2.   0.3  4.  10.   2.7]

k smallest values:
[0.3 1.  2.  2.7]
Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[12]
initial array :  [1.  1.4 2.7 2.  3.  2. ]
final array [1.4 2.7]
Original array:
[1050 5400 6250 1674 1685 5237 4545]
Indices of the sorted elements of a given array:
[0 3 4 6 5 1 2]


5. NumPy Random Exercises

In [ ]:
# Create a NumPy arrayu with random values.
import numpy as np

# if the shape is not mentioned the output will just be a random integer in the given range
rand_int = np.random.randint(5,10)
print("First array", rand_int)

rand_int2 = np.random.randint(10,90,(4,5)) # random numpy array of shape (4,5)
print("Second array", rand_int2)

rand_int3 = np.random.randint(50,75,(2,2), dtype='int64')
print("Third array", rand_int3)

# Generate Random numbers from the uniform distribution using NumPy.
import numpy
import random
random_number=numpy.random.uniform(1.3 , 4.2)
uniform_distrib= print("The Random number from uniform distribution is:",random_number)

# Return a Matrix of random values from a uniform distribution.
# Get the uniform random samples
arr = np.random.uniform(low = 3, high = 5, size = 5)
print(arr)

# Return a Matrix of random values from a Gaussian distribution.
from numpy import random

x = random.normal(loc=1, scale=2, size=(2, 3))

print(x)



First array 9
Second array [[51 75 54 56 27]
 [51 69 62 80 41]
 [87 62 34 12 60]
 [24 84 37 88 64]]
Third array [[70 63]
 [63 63]]
The Random number from uniform distribution is: 2.6937763772988577
[3.95586099 3.19437716 4.60048485 4.37225199 4.43426742]
[[-0.1827203  -1.08617858  2.65971   ]
 [-1.76562859  1.80133428  2.0465013 ]]


6. Pandas Dataframe Exercises

In [ ]:
# Make a Pandas DataFrame with two-dimnesional list.
import pandas as pd

# List1
lst = [['tom', 'reacher', 25], ['krish', 'pete', 30],
       ['nick', 'wilson', 26], ['juli', 'williams', 22]]

df = pd.DataFrame(lst, columns =['FName', 'LName', 'Age'],
                                           dtype = float)
print(df)

# Creating DataFrame from dict of narray/lists.
import pandas as pd

# initialise data of lists.
data = {'Category':['Array', 'Stack', 'Queue'],
        'Marks':[20, 21, 19]}

# Create DataFrame
df = pd.DataFrame(data)

# Print the output.
print(df )

# Creating Pandas dataframe using list of lists.
# importing the pandas package
import pandas as pd
# creating a nested list
nested_list = [[1,2,3],[10,20,30],[100,200,300]]

# creating DataFrame
df = pd.DataFrame(nested_list, columns= ['A','B','C'])

print(df)

# Creating a Pandas dataframe using list of tuples.
import pandas as pd

# data in the form of list of tuples
data = [('Karim', 18, 7),
        ('Masud', 15, 6),
        ('Johir', 17, 8),
        ('Rana', 18, 7),
        ('Tarek', 17, 5) ]


# create DataFrame using data
df = pd.DataFrame(data, columns =['Name', 'Age', 'Score'])

print(df)

# Create a Pandas DataFrame from list of dicts.
import pandas as pd

listOfDict = [{'Name': 'Aditya', 'Roll': 1, 'Language': 'Python'}, {'Name': 'Sam', 'Roll': 2, 'Language': 'Java'},
              {'Name': 'Chris', 'Roll': 3, 'Language': 'C++'}, {'Name': 'Joel', 'Roll': 4, 'Language': 'TypeScript'}]
print("THe list of dictionaries is:")
print(listOfDict)
df = pd.DataFrame(listOfDict)
print("The dataframe is:")
print(df)

# Creating a dataframe from Pandas series.
import pandas as pd

# Creating a list
author = ['Jamal', 'Pulok',
          'Arif', 'Joy']
# Creating a Series by passing list
# variable to Series() function
auth_series = pd.Series(author)
# Printing Series
print(auth_series)

# Reindexing in Pandas Dataframe.
import pandas as pd

data = {
  "age": [50, 40, 30, 40],
  "qualified": [True, False, False, False]
}
idx = ["Salam", "Mamun", "Jamal", "Monir"]
df = pd.DataFrame(data, index=idx)

newidx = ["Roy", "Chanchal", "Anik", "Paban"]
newdf = df.reindex(newidx)
print(newdf)

# Reset Index in Pandas Dataframe.
import numpy as np

student_dict = {'Name': ['Joy', 'Nirmol', np.NaN, 'Hamid'], 'Age': [20, 21, np.NaN, 19],
                'Marks': [85.10, 77.80, np.NaN, 91.54]}

# create DataFrame from dict
student_df = pd.DataFrame(student_dict, index=['s1', 's2', 's3', 's4'])
print(student_df)

# drop NA
student_df = student_df.dropna()
print(student_df)

# reset index
student_df = student_df.reset_index()
print(student_df)

# Change column names and row indexes in Pandas dataframe.

import pandas as pd

# Sample DataFrame
df = pd.DataFrame({'a': [1, 2], 'b': [3, 4]})

# Changing columns name with index number
df.columns.values[0] = "b"
df.columns.values[1] = "a"

# Display
display(df)



   FName     LName   Age
0    tom   reacher  25.0
1  krish      pete  30.0
2   nick    wilson  26.0
3   juli  williams  22.0
  Category  Marks
0    Array     20
1    Stack     21
2    Queue     19
     A    B    C
0    1    2    3
1   10   20   30
2  100  200  300
    Name  Age  Score
0  Karim   18      7
1  Masud   15      6
2  Johir   17      8
3   Rana   18      7
4  Tarek   17      5
THe list of dictionaries is:
[{'Name': 'Aditya', 'Roll': 1, 'Language': 'Python'}, {'Name': 'Sam', 'Roll': 2, 'Language': 'Java'}, {'Name': 'Chris', 'Roll': 3, 'Language': 'C++'}, {'Name': 'Joel', 'Roll': 4, 'Language': 'TypeScript'}]
The dataframe is:
     Name  Roll    Language
0  Aditya     1      Python
1     Sam     2        Java
2   Chris     3         C++
3    Joel     4  TypeScript
0    Jamal
1    Pulok
2     Arif
3      Joy
dtype: object
          age qualified
Roy       NaN       NaN
Chanchal  NaN       NaN
Anik      NaN       NaN
Paban     NaN       NaN
      Name   Age  Marks
s1     Joy  20

<ipython-input-42-af4240636437>:8: FutureWarning: Could not cast to float64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised.
  df = pd.DataFrame(lst, columns =['FName', 'LName', 'Age'],


b  a
0  1  3
1  2  4

7. Pandas Dataframe Row Exercises

In [14]:
# How to iterate over rows in Pandas Dataframe.
import pandas as pd

df = pd.DataFrame({'c1': [10, 11, 12], 'c2': [100, 110, 120]})
df = df.reset_index()  # make sure indexes pair with number of rows

for index, row in df.iterrows():
    print(row['c1'], row['c2'])

# Different ways to iterate over rows im Pandas dataframe.
import pandas as pd

# Define a dictionary containing students data
data = {'Name': ['Anik', 'Arif',
                 'Akhi', 'Purnima'],
        'Age': [21, 19, 20, 18],
        'Subject': ['Math', 'Statistics',
                   'Bangla', 'Biology'],
        'Percentage': [88, 92, 95, 70]}

# Convert the dictionary into DataFrame
df = pd.DataFrame(data, columns=['Name', 'Age',
                                 'Subject', 'Percentage'])

print("Given Dataframe :\n", df)

print("\nIterating over rows using index attribute :\n")

# iterate through each row and select
# 'Name' and 'Stream' column respectively.
for ind in df.index:
    print(df['Name'][ind], df['Subject'][ind])

# Selecting rows in Pandas Dataframe based on conditions.
import pandas as pd
import numpy as np
df = pd.DataFrame()
df['Name'] = ['Shaan', 'Dip', 'Noman','Jalil','Kalam','Bimal']
df['TotalMarks'] = [80, 40, 68,27,59,45]
df['Grade'] = ['A', 'E', 'B','E','C','D']
df['Promoted'] = [True, False,True,False,True,True]
df

# Select any row from a Dataframe using iloc[] and iat[] in Pandas.
import pandas as pd

# Create the dataframe
df = pd.DataFrame({'Date':['10/2/2022', '11/2/2022', '12/2/2022', '13/2/2022'],
                    'Event':['Music', 'Poetry', 'Theatre', 'Comedy'],
                    'Cost':[10000, 5000, 15000, 2000]})

# Create an empty list
Row_list =[]

# Iterate over each row
for i in range((df.shape[0])):

    # Using iloc to access the values of
    # the current row denoted by "i"
    Row_list.append(list(df.iloc[i, :]))

# Print the first 3 elements
print(Row_list[:3])

# Limited rows selection with given column in Pandas | Python.
# Import pandas package
import pandas as pd

# Define a dictionary containing employee data
data = {'Name':['Jony', 'Palak', 'Golam', 'Aman'],
        'Age':[27, 24, 22, 32],
        'Address':['Dhaka', 'Khulna', 'Rajshahi', 'Barishal'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}

# Convert the dictionary into DataFrame
df = pd.DataFrame(data)

# select three rows and two columns
print(df.loc[1:3, ['Name', 'Qualification']])

# Drop rows from the dataframe based on certain condition applied on column.

# Create pandas DataFrame
import pandas as pd
import numpy as np
technologies = {
    'Courses':["Spark","PySpark","Hadoop","Python"],
    'Fee' :[22000,25000,np.nan,24000],
    'Duration':['30day',None,'55days',np.nan],
    'Discount':[1000,2300,1000,np.nan]
          }
df = pd.DataFrame(technologies)
print(df)

df.drop(df[df['Fee'] >= 24000].index, inplace = True)
print(df)

# Insert row at given position in Pandas dataframe.
import pandas as pd
# create Pandas dataframe
my_data = pd.DataFrame({"x1":["a", "b", "c", "b"],
                        "x2":range(16, 20),
                        "x3":range(1, 5),
                        "x4":["a", "b", "c", "d"]})
print(my_data)

# Create list
my_row = [11, 22, 33, 44]
print(my_row)
# Create copy of DataFrame
# Create copy of DataFrame
# Reorder DataFrame
data_new = my_data.copy()
data_new.loc[1.5] = my_row
data_new = data_new.sort_index().reset_index(drop = True)
print(data_new)

# Create a list from rows in Pandas Dataframe.
import pandas as pd

# Create the dataframe
df = pd.DataFrame({'Date':['10/2/2022', '11/2/2022', '12/2/2022', '13/2/2022'],
                    'Event':['Music', 'Poetry', 'Theatre', 'Comedy'],
                    'Cost':[10000, 5000, 15000, 2000]})

# Print the dataframe
print(df)

# Create an empty list
Row_list =[]

# Iterate over each row
for rows in df.itertuples():
    # Create list for the current row
    my_list =[rows.Date, rows.Event, rows.Cost]

    # append the list to the final list
    Row_list.append(my_list)

# Print the list
print(Row_list)

# Ranking rows of Pandas Dataframe.
# import the required packages
import pandas as pd

# Define the dictionary for converting to dataframe
movies = {'Name': ['The Godfather', 'Bird Box', 'Fight Club'],
         'Year': ['1972', '2018', '1999'],
         'Rating': ['9.2', '6.8', '8.8']}

df = pd.DataFrame(movies)
print(df)
# Create a column Rating_Rank which contains
# the rank of each movie based on rating
df['Rating_Rank'] = df['Rating'].rank(ascending = 1)

# Set the index to newly created column, Rating_Rank
df = df.set_index('Rating_Rank')
print(df)
# Sort the dataFrame based on the index
df = df.sort_index()
print(df)

# Sorting rows in Pandas Dataframe.
import pandas as pd

# create dataframe
data = {'name': ['Sajal', 'Mamun', 'Galiv', 'Alif', 'Jaman'],
        'Maths': [8, 5, 6, 9, 7],
        'Science': [7, 9, 5, 4, 7],
        'English': [7, 4, 7, 6, 8]}

df = pd.DataFrame(data)

# Sort the dataframe’s rows by Science,
# in descending order
a = df.sort_values(by ='Science', ascending = 0)
print("Sorting rows by Science:\n \n", a)
import pandas as pd

# create dataframe
data = {'name': ['Sajal', 'Mamun', 'Galiv', 'Alif', 'Jaman'],
        'Maths': [8, 5, 6, 9, 7],
        'Science': [7, 9, 5, 4, 7],
        'English': [7, 4, 7, 6, 8]}

df = pd.DataFrame(data)

# Sort the dataframe’s rows by Maths
# and then by English, in ascending order
b = df.sort_values(by =['Maths', 'English'])
print("Sort rows by Maths and then by English: \n\n", b)

# Select row with maximum and minimum value in Pandas dataframe.
import pandas as pd
# Create example DataFrame
data = pd.DataFrame({'x1':[3, 2, 7, 1, 9, 3, 4],
                     'x2':[2, 1, 1, 3, 1, 2, 3],
                     'x3':range(7, 0, - 1)})
print(data)
# Maximum in column
my_max = data['x1'].loc[data['x1'].idxmax()]
print(my_max)
# Minimum in column
my_min = data['x1'].loc[data['x1'].idxmin()]
print(my_min)

# Get all rows in a Pandas Dataframe containing given substring.
import pandas as pd

data = {'month': ['January','February','March','April','May','June','July','August','September','October','November','December'],
        'days_in_month': [31,28,31,30,31,30,31,31,30,31,30,31]
        }

df = pd.DataFrame(data, columns = ['month', 'days_in_month'])

contain_values = df[df['month'].str.contains('Ju')]
print (contain_values)

# Convert a column to row name/index in Pandas.
import pandas as pd

# Creating a dict of lists
data = {'Name':["Akash", "Golam", "Palak", "Sumon","Raju"],
       'Branch':["M.Sc", "MBA", "BBA", "B.Sc", "BCA"],
       'Score':["80","90","60", "30", "50"],
       'Result': ["Pass","Pass","Pass","Fail","Fail"]}

# creating a dataframe
df = pd.DataFrame(data)

df
# Creating a dataframe
df = pd.DataFrame(data)

# Using set_index() method on 'Name' column
df = df.set_index('Name')

df


# How to randomly select rows from Pandas Dataframe.
# Import pandas package
import pandas as pd

# Define a dictionary containing employee data
data = {'Name':['Jamal', 'Prince', 'Galiv', 'Anik', 'Karim'],
        'Age':[27, 24, 22, 32, 15],
        'Address':['Dhaka', 'Khulna', 'Narayanganj', 'Kashimpur', 'Sylhet'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd', 'HSc']}

# Convert the dictionary into DataFrame
df = pd.DataFrame(data)

# Select one row randomly using sample()
# without give any parameters
df.sample()







10 100
11 110
12 120
Given Dataframe :
       Name  Age     Subject  Percentage
0     Anik   21        Math          88
1     Arif   19  Statistics          92
2     Akhi   20      Bangla          95
3  Purnima   18     Biology          70

Iterating over rows using index attribute :

Anik Math
Arif Statistics
Akhi Bangla
Purnima Biology
[['10/2/2022', 'Music', 10000], ['11/2/2022', 'Poetry', 5000], ['12/2/2022', 'Theatre', 15000]]
    Name Qualification
1  Palak            MA
2  Golam           MCA
3   Aman           Phd
   Courses      Fee Duration  Discount
0    Spark  22000.0    30day    1000.0
1  PySpark  25000.0     None    2300.0
2   Hadoop      NaN   55days    1000.0
3   Python  24000.0      NaN       NaN
  Courses      Fee Duration  Discount
0   Spark  22000.0    30day    1000.0
2  Hadoop      NaN   55days    1000.0
  x1  x2  x3 x4
0  a  16   1  a
1  b  17   2  b
2  c  18   3  c
3  b  19   4  d
[11, 22, 33, 44]
   x1  x2  x3  x4
0   a  16   1   a
1   b  17   2   b
2  11  22  3

Name  Age      Address Qualification
2  Galiv   22  Narayanganj           MCA

8. Pandas Dataframe Columns Exercises

In [37]:
# Create a Pandas column using for loop.
import pandas as pd

# Creating new dataframe
initial_data = {'First_name': ['Raju', 'Mohammad', 'Tarikul', 'Jamal', 'Mim'],
                'Last_name': ['Ahmed', 'Ali', 'Alam', 'Haque', 'Siddique'],
                'Marks': [12, 52, 36, 85, 23] }

df = pd.DataFrame(initial_data, columns = ['First_name', 'Last_name', 'Marks'])

# Generate result using pandas
result = []
for value in df["Marks"]:
    if value >= 33:
        result.append("Pass")
    elif value < 0 and value > 100:
        result.append("Invalid")
    else:
        result.append("Fail")

df["Result"] = result
print(df)

# How to get column names in Pandas dataframe.

import pandas as pd
import numpy as np

technologies= {
    'Courses':["Spark","PySpark","Hadoop","Python","Pandas"],
    'Fee' :[22000,25000,23000,24000,26000],
    'Duration':['30days','50days','30days', None,np.nan],
    'Discount':[1000,2300,1000,1200,2500]
          }
df = pd.DataFrame(technologies)
print(df)

# Get the list of all column names from headers
column_headers = list(df.columns.values)
print("The Column Header :", column_headers)

# How to rename columns in Pandas Dataframe.
import pandas as pd

# Define a dictionary containing ICC rankings
rankings = {'test': ['India', 'South Africa', 'England',
                            'New Zealand', 'Australia'],
              'odi': ['England', 'India', 'New Zealand',
                            'South Africa', 'Pakistan'],
               't20': ['Pakistan', 'India', 'Australia',
                              'England', 'New Zealand']}

# Convert the dictionary into DataFrame
rankings_pd = pd.DataFrame(rankings)

# Before renaming the columns
print(rankings_pd.columns)

rankings_pd.rename(columns = {'test':'TEST', 'odi':'ODI',
                              't20':'T20'}, inplace = True)

# After renaming the columns
print(rankings_pd.columns)

# Get unique values from a column in pandas dataframe.
import pandas as pd

# create a dictionary with five fields each
data = {
    'A':['A1', 'A2', 'A3', 'A4', 'A5'],
    'B':['B1', 'B2', 'B3', 'B4', 'B4'],
    'C':['C1', 'C2', 'C3', 'C3', 'C3'],
    'D':['D1', 'D2', 'D2', 'D2', 'D2'],
    'E':['E1', 'E1', 'E1', 'E1', 'E1'] }

# Convert the dictionary into DataFrame
df = pd.DataFrame(data)

# Get the unique values of 'B' column
df.B.unique()

# Return the index label if some condition is satisfied over a column inPandas dataframe.
import pandas as pd

# Create the dataframe
df = pd.DataFrame({'Date':['10/2/2022', '11/2/2022', '12/2/2022', '13/2/2022'],
                   'Product':['Umbrella', 'Mattress', 'Badminton', 'Shuttle'],
                   'Last_Price':[1200, 1500, 1600, 352],
                   'Updated_Price':[1250, 1450, 1550, 400],
                   'Discount':[10, 10, 10, 10]})

# Create the indexes
df.index =['Item 1', 'Item 2', 'Item 3', 'Item 4']

# Print the dataframe
print(df)
# Select all the rows which satisfies the criteria
# convert the collection of index labels to list.
Index_label = df[df['Updated_Price']>1000].index.tolist()

# Print all the labels
print(Index_label)

# Create a new column in Pandas Dataframe based on the exixting columns.
import pandas as pd

# Creating the DataFrame
df = pd.DataFrame({'Date':['10/2/2022', '11/2/2022', '12/2/2022', '13/2/2022'],
                    'Event':['Music', 'Poetry', 'Theatre', 'Comedy'],
                    'Cost':[10000, 5000, 15000, 2000]})

# Print the dataframe
print(df)
# using apply function to create a new column
df['Discounted_Price'] = df.apply(lambda row: row.Cost -
                                  (row.Cost * 0.1), axis = 1)

# Print the DataFrame after addition
# of new column
print(df)

# Creating a Pandas dataframe column based on a given condition.
import pandas as pd

# Creating the dataframe
df = pd.DataFrame({'Date' : ['11/8/2022', '11/9/2022', '11/10/2022',
                                        '11/11/2022', '11/12/2022'],
                'Event' : ['Music', 'Poetry', 'Music', 'Comedy', 'Poetry']})

# Print the dataframe
print(df)
# Add a new column named 'Price'
df['Price'] = [1500 if x =='Music' else 800 for x in df['Event']]

# Print the DataFrame
print(df)

# Getting Unique values from a column in Pandas Dataframe.
import pandas as pd

data = {
  "Students": ["Rahman", "Jolly", "Molly", "Smrity", "Jamal", "Milli", "Tonmoy", "Raju"],
  "Subjects": ["Maths", "Economics", "Science", "Maths", "Statistics", "Statistics", "Statistics", "Computers"]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df["Subjects"].unique())
print(type(df["Subjects"].unique()))

# Getting frequency counts of a columns in Pandas Dataframe.
import pandas as pd

# sample dataframe
df = pd.DataFrame({'A': ['foo', 'bar', 'g2g', 'g2g', 'g2g',
                         'bar', 'bar', 'foo', 'bar'],
                  'B': ['a', 'b', 'a', 'b', 'b', 'b', 'a', 'a', 'b'] })

# frequency count of column A
count = df['A'].value_counts()
print(count)

# Split a text column into two columns in Pandas dataframe.
import pandas as pd

# create a new data frame
df = pd.DataFrame({'Name': ['Jaman Uddin', 'Rana Khan', 'Forhad Hossein'],
                   'Age':[32, 34, 36]})

print("Given Dataframe is :\n",df)

# bydefault splitting is done on the basis of single space.
print("\nSplitting 'Name' column into two different columns :\n",
                                  df.Name.str.split(expand=True))

# Get the index of minimum value in Dataframe column
import pandas as pd
data = pd.DataFrame({'x1':[3, 2, 7, 1, 9, 3, 4],
                     'x2':[2, 1, 1, 3, 1, 2, 3],
                     'x3':range(7, 0, - 1)})
print(data)
my_min = data['x1'].loc[data['x1'].idxmin()]
print(my_min)

# Get the index of maximum value in Dataframe column.
import pandas as pd
data = pd.DataFrame({'x1':[3, 2, 7, 1, 9, 3, 4],
                     'x2':[2, 1, 1, 3, 1, 2, 3],
                     'x3':range(7, 0, - 1)})
print(data)
my_max = data['x1'].loc[data['x1'].idxmax()]
print(my_max)

# Difference of two columns in Pandas dataframe.
import pandas as pd
data = pd.DataFrame({'x1':[1, 3, 2, 4, 7, 5],
                     'x2':['a', 'b', 'c', 'd', 'e', 'f'],
                     'x3':range(1, 7)})
print(data)
print(data['x1'].equals(data['x3']))             # Apply equals function

# Get n-largest values from a particular column in Pandas Dataframe.
# Get n-smallest values from a particular column in Pandas Dataframe.

# How to drop one or multiple columns in Pandas Dataframe.
import pandas as pd

# create a dictionary with five fields each
data = {
    'A': ['A1', 'A2', 'A3', 'A4', 'A5'],
    'B': ['B1', 'B2', 'B3', 'B4', 'B5'],
    'C': ['C1', 'C2', 'C3', 'C4', 'C5'],
    'D': ['D1', 'D2', 'D3', 'D4', 'D5'],
    'E': ['E1', 'E2', 'E3', 'E4', 'E5']}

# Convert the dictionary into DataFrame
df = pd.DataFrame(data)

df
# Convert the dictionary into DataFrame
df = pd.DataFrame(data)

# Remove two columns name is 'C' and 'D'
df.drop(['C', 'D'], axis=1)

# df.drop(columns =['C', 'D'])








  First_name Last_name  Marks Result
0       Raju     Ahmed     12   Fail
1   Mohammad       Ali     52   Pass
2    Tarikul      Alam     36   Pass
3      Jamal     Haque     85   Pass
4        Mim  Siddique     23   Fail
   Courses    Fee Duration  Discount
0    Spark  22000   30days      1000
1  PySpark  25000   50days      2300
2   Hadoop  23000   30days      1000
3   Python  24000     None      1200
4   Pandas  26000      NaN      2500
The Column Header : ['Courses', 'Fee', 'Duration', 'Discount']
Index(['test', 'odi', 't20'], dtype='object')
Index(['TEST', 'ODI', 'T20'], dtype='object')
             Date    Product  Last_Price  Updated_Price  Discount
Item 1  10/2/2022   Umbrella        1200           1250        10
Item 2  11/2/2022   Mattress        1500           1450        10
Item 3  12/2/2022  Badminton        1600           1550        10
Item 4  13/2/2022    Shuttle         352            400        10
['Item 1', 'Item 2', 'Item 3']
        Date    Event   Cost
0  10/2/202

A   B   E
0  A1  B1  E1
1  A2  B2  E2
2  A3  B3  E3
3  A4  B4  E4
4  A5  B5  E5

9. Pandas Series - Practices Exercises

In [43]:
# Create a Pandas Series from array.
import pandas as pd
import numpy as np

# numpy array
data = np.array(['a', 'b', 'c', 'd', 'e'])

# creating series
s = pd.Series(data)
print(s)

# Creating a pandas series from dictionary.
import pandas as pd

# create a dictionary
dictionary = {'A': 10, 'B': 20, 'C': 30}

# create a series
series = pd.Series(dictionary)

print(series)

# Creating a pandas series from lists.
import pandas as pd

# create Pandas Series with define indexes
x = pd.Series([10, 20, 30, 40, 50], index =['a', 'b', 'c', 'd', 'e'])

# print the Series
print(x)

# Create Pandas Series using Numpy functions.
import pandas as pd
import numpy as np

# series with numpy linspace()
ser1 = pd.Series(np.linspace(3, 33, 3))
print(ser1)

# series with numpy linspace()
ser2 = pd.Series(np.linspace(1, 100, 10))
print("\n", ser2)

# Access the elements of a series in Pandas.
import pandas as pd
import numpy as np

# creating simple array
data = np.array(['g', 'e', 'e', 'k', 's', 'f', 'o', 'r', 'g', 'e', 'e', 'k', 's'])
ser = pd.Series(data)


# retrieve the first element
print(ser[0])

import pandas as pd
import numpy as np

# creating simple array
data = np.array(['g', 'e', 'e', 'k', 's', 'f', 'o', 'r', 'g', 'e', 'e', 'k', 's'])
ser = pd.Series(data)


# retrieve the first element
print(ser[:5])


0    a
1    b
2    c
3    d
4    e
dtype: object
A    10
B    20
C    30
dtype: int64
a    10
b    20
c    30
d    40
e    50
dtype: int64
0     3.0
1    18.0
2    33.0
dtype: float64

 0      1.0
1     12.0
2     23.0
3     34.0
4     45.0
5     56.0
6     67.0
7     78.0
8     89.0
9    100.0
dtype: float64
g
0    g
1    e
2    e
3    k
4    s
dtype: object


10. Pandas Datetime Exercises

In [44]:
# Convert the column type from string to datetime format in Pandas dataframe.
import pandas as pd

# Creating the dataframe
df = pd.DataFrame({'Date':['11/8/2022', '04/23/2018', '10/2/2014'],
                'Event':['Music', 'Poetry', 'Theatre'],
                'Cost':[10000, 5000, 15000]})

# Print the dataframe
print(df)

# Now we will check the data type
# of the 'Date' column
df.info()
# convert the 'Date' column to datetime format
df['Date']= pd.to_datetime(df['Date'])

# Check the format of 'Date' column
df.info()

         Date    Event   Cost
0   11/8/2022    Music  10000
1  04/23/2018   Poetry   5000
2   10/2/2014  Theatre  15000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Date    3 non-null      object
 1   Event   3 non-null      object
 2   Cost    3 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 200.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   Date    3 non-null      datetime64[ns]
 1   Event   3 non-null      object        
 2   Cost    3 non-null      int64         
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 200.0+ bytes


                                                Thank You